# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_server.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1012, 705)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background2 = QtWidgets.QWidget(self.centralwidget)
        self.background2.setGeometry(QtCore.QRect(350, 10, 311, 641))
        self.background2.setStyleSheet("background-color: rgb(221, 221, 221)")
        self.background2.setObjectName("background2")
        self.commands_background = QtWidgets.QWidget(self.background2)
        self.commands_background.setGeometry(QtCore.QRect(0, 20, 311, 51))
        self.commands_background.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commands_background.setAutoFillBackground(False)
        self.commands_background.setStyleSheet("QWidget {\n"
"    background-color: #ffc355; /* cor de fundo amarela */\n"
"    /*border-radius: 10px;*/\n"
"\n"
"}\n"
"")
        self.commands_background.setObjectName("commands_background")
        self.commands_label = QtWidgets.QLabel(self.commands_background)
        self.commands_label.setGeometry(QtCore.QRect(90, 10, 131, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.commands_label.setFont(font)
        self.commands_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commands_label.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.commands_label.setAlignment(QtCore.Qt.AlignCenter)
        self.commands_label.setWordWrap(False)
        self.commands_label.setObjectName("commands_label")
        self.table_request = QtWidgets.QLabel(self.background2)
        self.table_request.setGeometry(QtCore.QRect(40, 90, 121, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.table_request.setFont(font)
        self.table_request.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.table_request.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.table_request.setAlignment(QtCore.Qt.AlignCenter)
        self.table_request.setWordWrap(False)
        self.table_request.setObjectName("table_request")
        self.execute_table = QtWidgets.QPushButton(self.background2)
        self.execute_table.setGeometry(QtCore.QRect(50, 210, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.execute_table.setFont(font)
        self.execute_table.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.execute_table.setObjectName("execute_table")
        self.download_csv = QtWidgets.QPushButton(self.background2)
        self.download_csv.setGeometry(QtCore.QRect(50, 290, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.download_csv.setFont(font)
        self.download_csv.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.download_csv.setObjectName("download_csv")
        self.lineEdit1 = QtWidgets.QLineEdit(self.background2)
        self.lineEdit1.setGeometry(QtCore.QRect(40, 130, 201, 31))
        self.lineEdit1.setStyleSheet("    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; ")
        self.lineEdit1.setObjectName("lineEdit1")
        self.background1 = QtWidgets.QWidget(self.centralwidget)
        self.background1.setGeometry(QtCore.QRect(20, 10, 311, 641))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.background1.setFont(font)
        self.background1.setStyleSheet("background-color: rgb(221, 221, 221)")
        self.background1.setObjectName("background1")
        self.configuration_background = QtWidgets.QWidget(self.background1)
        self.configuration_background.setGeometry(QtCore.QRect(0, 20, 311, 51))
        self.configuration_background.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.configuration_background.setAutoFillBackground(False)
        self.configuration_background.setStyleSheet("QWidget {\n"
"    background-color: #ffc355; /* cor de fundo amarela */\n"
"    /*border-radius: 10px;*/\n"
"\n"
"}\n"
"")
        self.configuration_background.setObjectName("configuration_background")
        self.configuration_label = QtWidgets.QLabel(self.configuration_background)
        self.configuration_label.setGeometry(QtCore.QRect(70, 10, 171, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.configuration_label.setFont(font)
        self.configuration_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.configuration_label.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.configuration_label.setAlignment(QtCore.Qt.AlignCenter)
        self.configuration_label.setWordWrap(False)
        self.configuration_label.setObjectName("configuration_label")
        self.host = QtWidgets.QLabel(self.background1)
        self.host.setGeometry(QtCore.QRect(40, 90, 51, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.host.setFont(font)
        self.host.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.host.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.host.setAlignment(QtCore.Qt.AlignCenter)
        self.host.setWordWrap(False)
        self.host.setObjectName("host")
        self.user = QtWidgets.QLabel(self.background1)
        self.user.setGeometry(QtCore.QRect(40, 220, 51, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.user.setFont(font)
        self.user.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.user.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.user.setAlignment(QtCore.Qt.AlignCenter)
        self.user.setWordWrap(False)
        self.user.setObjectName("user")
        self.password = QtWidgets.QLabel(self.background1)
        self.password.setGeometry(QtCore.QRect(40, 360, 91, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.password.setFont(font)
        self.password.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.password.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.password.setAlignment(QtCore.Qt.AlignCenter)
        self.password.setWordWrap(False)
        self.password.setObjectName("password")
        self.database = QtWidgets.QLabel(self.background1)
        self.database.setGeometry(QtCore.QRect(40, 500, 91, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.database.setFont(font)
        self.database.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.database.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.database.setAlignment(QtCore.Qt.AlignCenter)
        self.database.setWordWrap(False)
        self.database.setObjectName("database")
        self.lineEdit2 = QtWidgets.QLineEdit(self.background1)
        self.lineEdit2.setGeometry(QtCore.QRect(40, 130, 201, 31))
        self.lineEdit2.setStyleSheet("    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; ")
        self.lineEdit2.setObjectName("lineEdit2")
        self.lineEdit3 = QtWidgets.QLineEdit(self.background1)
        self.lineEdit3.setGeometry(QtCore.QRect(40, 260, 201, 31))
        self.lineEdit3.setStyleSheet("    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; ")
        self.lineEdit3.setObjectName("lineEdit3")
        self.lineEdit4 = QtWidgets.QLineEdit(self.background1)
        self.lineEdit4.setGeometry(QtCore.QRect(40, 400, 201, 31))
        self.lineEdit4.setStyleSheet("    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; ")
        self.lineEdit4.setObjectName("lineEdit4")
        self.lineEdit5 = QtWidgets.QLineEdit(self.background1)
        self.lineEdit5.setGeometry(QtCore.QRect(40, 540, 201, 31))
        self.lineEdit5.setStyleSheet("    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; ")
        self.lineEdit5.setObjectName("lineEdit5")
        self.background3 = QtWidgets.QWidget(self.centralwidget)
        self.background3.setGeometry(QtCore.QRect(680, 10, 311, 641))
        self.background3.setStyleSheet("background-color: rgb(221, 221, 221)")
        self.background3.setObjectName("background3")
        self.execute_background = QtWidgets.QWidget(self.background3)
        self.execute_background.setGeometry(QtCore.QRect(0, 20, 311, 51))
        self.execute_background.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.execute_background.setAutoFillBackground(False)
        self.execute_background.setStyleSheet("QWidget {\n"
"    background-color: #ffc355; /* cor de fundo amarela */\n"
"    /*border-radius: 10px;*/\n"
"\n"
"}\n"
"")
        self.execute_background.setObjectName("execute_background")
        self.execute_label = QtWidgets.QLabel(self.execute_background)
        self.execute_label.setGeometry(QtCore.QRect(100, 10, 111, 30))
        self.execute_label.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.execute_label.setFont(font)
        self.execute_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.execute_label.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.execute_label.setAlignment(QtCore.Qt.AlignCenter)
        self.execute_label.setWordWrap(False)
        self.execute_label.setObjectName("execute_label")
        self.send_parameters = QtWidgets.QPushButton(self.background3)
        self.send_parameters.setGeometry(QtCore.QRect(60, 110, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.send_parameters.setFont(font)
        self.send_parameters.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.send_parameters.setObjectName("send_parameters")
        self.download_json = QtWidgets.QPushButton(self.background3)
        self.download_json.setGeometry(QtCore.QRect(60, 280, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.download_json.setFont(font)
        self.download_json.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.download_json.setObjectName("download_json")
        self.upload_json = QtWidgets.QPushButton(self.background3)
        self.upload_json.setGeometry(QtCore.QRect(60, 350, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.upload_json.setFont(font)
        self.upload_json.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.upload_json.setObjectName("upload_json")
        self.clear_fields = QtWidgets.QPushButton(self.background3)
        self.clear_fields.setGeometry(QtCore.QRect(60, 490, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.clear_fields.setFont(font)
        self.clear_fields.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.clear_fields.setObjectName("clear_fields")
        self.file_name = QtWidgets.QLabel(self.background3)
        self.file_name.setGeometry(QtCore.QRect(60, 220, 90, 16))
        self.file_name.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.file_name.setFont(font)
        self.file_name.setObjectName("file_name")
        self.file_name_input = QtWidgets.QLineEdit(self.background3)
        self.file_name_input.setGeometry(QtCore.QRect(60, 240, 181, 31))
        self.file_name_input.setStyleSheet("QLineEdit {\n"
"    background-color: white; /* Define o fundo como branco */\n"
"    border: 1px solid #a9a9a9; /* Define uma borda sólida com cor cinza */\n"
"    border-radius: 5px; /* Cantos arredondados com raio de 5px */\n"
"    padding: 1px 3px; /* Espaçamento interno para o texto não tocar a borda */\n"
"}\n"
"")
        self.file_name_input.setObjectName("file_name_input")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1012, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "data_server"))
        self.commands_label.setText(_translate("MainWindow", "Commands"))
        self.table_request.setText(_translate("MainWindow", "Table request"))
        self.execute_table.setText(_translate("MainWindow", "Execute Table"))
        self.download_csv.setText(_translate("MainWindow", "Download CSV"))
        self.configuration_label.setText(_translate("MainWindow", "Configuration"))
        self.host.setText(_translate("MainWindow", "Host"))
        self.user.setText(_translate("MainWindow", "User"))
        self.password.setText(_translate("MainWindow", "Password"))
        self.database.setText(_translate("MainWindow", "Database"))
        self.execute_label.setText(_translate("MainWindow", "Execute"))
        self.send_parameters.setText(_translate("MainWindow", "Send Parameters"))
        self.download_json.setText(_translate("MainWindow", "Download JSON"))
        self.upload_json.setText(_translate("MainWindow", "Upload JSON"))
        self.clear_fields.setText(_translate("MainWindow", "Clear Fields"))
        self.file_name.setText(_translate("MainWindow", "File name:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
