# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'send_commands.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1012, 705)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background2 = QtWidgets.QWidget(self.centralwidget)
        self.background2.setGeometry(QtCore.QRect(350, 10, 311, 641))
        self.background2.setStyleSheet("background-color: rgb(221, 221, 221)")
        self.background2.setObjectName("background2")
        self.configuration_background = QtWidgets.QWidget(self.background2)
        self.configuration_background.setGeometry(QtCore.QRect(0, 20, 311, 51))
        self.configuration_background.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.configuration_background.setAutoFillBackground(False)
        self.configuration_background.setStyleSheet("QWidget {\n"
"    background-color: #ffc355; /* cor de fundo amarela */\n"
"    /*border-radius: 10px;*/\n"
"\n"
"}\n"
"")
        self.configuration_background.setObjectName("configuration_background")
        self.configuration_label = QtWidgets.QLabel(self.configuration_background)
        self.configuration_label.setGeometry(QtCore.QRect(60, 10, 191, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.configuration_label.setFont(font)
        self.configuration_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.configuration_label.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.configuration_label.setAlignment(QtCore.Qt.AlignCenter)
        self.configuration_label.setWordWrap(False)
        self.configuration_label.setObjectName("configuration_label")
        self.input_box1 = QtWidgets.QSpinBox(self.background2)
        self.input_box1.setGeometry(QtCore.QRect(40, 180, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_box1.setFont(font)
        self.input_box1.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_box1.setMinimum(-999999999)
        self.input_box1.setMaximum(999999999)
        self.input_box1.setObjectName("input_box1")
        self.move = QtWidgets.QLabel(self.background2)
        self.move.setGeometry(QtCore.QRect(40, 140, 71, 35))
        self.move.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.move.setFont(font)
        self.move.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.move.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.move.setAlignment(QtCore.Qt.AlignCenter)
        self.move.setWordWrap(False)
        self.move.setObjectName("move")
        self.rotate = QtWidgets.QLabel(self.background2)
        self.rotate.setGeometry(QtCore.QRect(40, 290, 71, 35))
        self.rotate.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.rotate.setFont(font)
        self.rotate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rotate.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.rotate.setAlignment(QtCore.Qt.AlignCenter)
        self.rotate.setWordWrap(False)
        self.rotate.setObjectName("rotate")
        self.input_box2 = QtWidgets.QSpinBox(self.background2)
        self.input_box2.setGeometry(QtCore.QRect(40, 330, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_box2.setFont(font)
        self.input_box2.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_box2.setMinimum(-999999999)
        self.input_box2.setMaximum(999999999)
        self.input_box2.setObjectName("input_box2")
        self.label_move = QtWidgets.QLabel(self.background2)
        self.label_move.setGeometry(QtCore.QRect(120, 140, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_move.setFont(font)
        self.label_move.setStyleSheet("  color: blue; ")
        self.label_move.setObjectName("label_move")
        self.label_rotate = QtWidgets.QLabel(self.background2)
        self.label_rotate.setGeometry(QtCore.QRect(120, 290, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_rotate.setFont(font)
        self.label_rotate.setStyleSheet("  color: blue; ")
        self.label_rotate.setObjectName("label_rotate")
        self.background1 = QtWidgets.QWidget(self.centralwidget)
        self.background1.setGeometry(QtCore.QRect(20, 10, 311, 641))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.background1.setFont(font)
        self.background1.setStyleSheet("background-color: rgb(221, 221, 221)")
        self.background1.setObjectName("background1")
        self.commands_background = QtWidgets.QWidget(self.background1)
        self.commands_background.setGeometry(QtCore.QRect(0, 20, 311, 51))
        self.commands_background.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commands_background.setAutoFillBackground(False)
        self.commands_background.setStyleSheet("QWidget {\n"
"    background-color: #ffc355; /* cor de fundo amarela */\n"
"    /*border-radius: 10px;*/\n"
"\n"
"}\n"
"")
        self.commands_background.setObjectName("commands_background")
        self.commands_label = QtWidgets.QLabel(self.commands_background)
        self.commands_label.setGeometry(QtCore.QRect(70, 10, 161, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.commands_label.setFont(font)
        self.commands_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commands_label.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.commands_label.setAlignment(QtCore.Qt.AlignCenter)
        self.commands_label.setWordWrap(False)
        self.commands_label.setObjectName("commands_label")
        self.exposures = QtWidgets.QPushButton(self.background1)
        self.exposures.setGeometry(QtCore.QRect(40, 120, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.exposures.setFont(font)
        self.exposures.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.exposures.setObjectName("exposures")
        self.start_ct = QtWidgets.QPushButton(self.background1)
        self.start_ct.setGeometry(QtCore.QRect(40, 220, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.start_ct.setFont(font)
        self.start_ct.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.start_ct.setObjectName("start_ct")
        self.origin = QtWidgets.QPushButton(self.background1)
        self.origin.setGeometry(QtCore.QRect(40, 320, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.origin.setFont(font)
        self.origin.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.origin.setObjectName("origin")
        self.zero_z = QtWidgets.QPushButton(self.background1)
        self.zero_z.setGeometry(QtCore.QRect(40, 520, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.zero_z.setFont(font)
        self.zero_z.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.zero_z.setObjectName("zero_z")
        self.zero_degree = QtWidgets.QPushButton(self.background1)
        self.zero_degree.setGeometry(QtCore.QRect(40, 420, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.zero_degree.setFont(font)
        self.zero_degree.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.zero_degree.setObjectName("zero_degree")
        self.label_exposures = QtWidgets.QLabel(self.background1)
        self.label_exposures.setGeometry(QtCore.QRect(240, 130, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_exposures.setFont(font)
        self.label_exposures.setStyleSheet("  color: blue; ")
        self.label_exposures.setObjectName("label_exposures")
        self.label_start_ct = QtWidgets.QLabel(self.background1)
        self.label_start_ct.setGeometry(QtCore.QRect(240, 230, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_start_ct.setFont(font)
        self.label_start_ct.setStyleSheet("  color: blue; ")
        self.label_start_ct.setObjectName("label_start_ct")
        self.label_origin = QtWidgets.QLabel(self.background1)
        self.label_origin.setGeometry(QtCore.QRect(240, 330, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_origin.setFont(font)
        self.label_origin.setStyleSheet("  color: blue; ")
        self.label_origin.setObjectName("label_origin")
        self.label_zero_degree = QtWidgets.QLabel(self.background1)
        self.label_zero_degree.setGeometry(QtCore.QRect(240, 430, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_zero_degree.setFont(font)
        self.label_zero_degree.setStyleSheet("  color: blue; ")
        self.label_zero_degree.setObjectName("label_zero_degree")
        self.label_zero_z = QtWidgets.QLabel(self.background1)
        self.label_zero_z.setGeometry(QtCore.QRect(240, 530, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_zero_z.setFont(font)
        self.label_zero_z.setStyleSheet("  color: blue; ")
        self.label_zero_z.setObjectName("label_zero_z")
        self.background3 = QtWidgets.QWidget(self.centralwidget)
        self.background3.setGeometry(QtCore.QRect(680, 10, 311, 641))
        self.background3.setStyleSheet("background-color: rgb(221, 221, 221)")
        self.background3.setObjectName("background3")
        self.execute_background = QtWidgets.QWidget(self.background3)
        self.execute_background.setGeometry(QtCore.QRect(0, 20, 311, 51))
        self.execute_background.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.execute_background.setAutoFillBackground(False)
        self.execute_background.setStyleSheet("QWidget {\n"
"    background-color: #ffc355; /* cor de fundo amarela */\n"
"    /*border-radius: 10px;*/\n"
"\n"
"}\n"
"")
        self.execute_background.setObjectName("execute_background")
        self.execute_label = QtWidgets.QLabel(self.execute_background)
        self.execute_label.setGeometry(QtCore.QRect(100, 10, 111, 30))
        self.execute_label.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.execute_label.setFont(font)
        self.execute_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.execute_label.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.execute_label.setAlignment(QtCore.Qt.AlignCenter)
        self.execute_label.setWordWrap(False)
        self.execute_label.setObjectName("execute_label")
        self.send_parameters = QtWidgets.QPushButton(self.background3)
        self.send_parameters.setGeometry(QtCore.QRect(60, 110, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.send_parameters.setFont(font)
        self.send_parameters.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.send_parameters.setObjectName("send_parameters")
        self.download_json = QtWidgets.QPushButton(self.background3)
        self.download_json.setGeometry(QtCore.QRect(60, 280, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.download_json.setFont(font)
        self.download_json.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.download_json.setObjectName("download_json")
        self.upload_json = QtWidgets.QPushButton(self.background3)
        self.upload_json.setGeometry(QtCore.QRect(60, 350, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.upload_json.setFont(font)
        self.upload_json.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.upload_json.setObjectName("upload_json")
        self.clear_fields = QtWidgets.QPushButton(self.background3)
        self.clear_fields.setGeometry(QtCore.QRect(60, 490, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.clear_fields.setFont(font)
        self.clear_fields.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.clear_fields.setObjectName("clear_fields")
        self.file_name = QtWidgets.QLabel(self.background3)
        self.file_name.setGeometry(QtCore.QRect(60, 220, 90, 16))
        self.file_name.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.file_name.setFont(font)
        self.file_name.setObjectName("file_name")
        self.file_name_input = QtWidgets.QLineEdit(self.background3)
        self.file_name_input.setGeometry(QtCore.QRect(60, 240, 181, 31))
        self.file_name_input.setStyleSheet("QLineEdit {\n"
"    background-color: white; /* Define o fundo como branco */\n"
"    border: 1px solid #a9a9a9; /* Define uma borda sólida com cor cinza */\n"
"    border-radius: 5px; /* Cantos arredondados com raio de 5px */\n"
"    padding: 1px 3px; /* Espaçamento interno para o texto não tocar a borda */\n"
"}\n"
"")
        self.file_name_input.setObjectName("file_name_input")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1012, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "send_commands"))
        self.configuration_label.setText(_translate("MainWindow", "Configuration"))
        self.move.setText(_translate("MainWindow", "Move"))
        self.rotate.setText(_translate("MainWindow", "Rotate"))
        self.label_move.setText(_translate("MainWindow", "?"))
        self.label_rotate.setText(_translate("MainWindow", "?"))
        self.commands_label.setText(_translate("MainWindow", "Commands"))
        self.exposures.setText(_translate("MainWindow", "Exposures"))
        self.start_ct.setText(_translate("MainWindow", "Start CT"))
        self.origin.setText(_translate("MainWindow", "Origin"))
        self.zero_z.setText(_translate("MainWindow", "Zero Z"))
        self.zero_degree.setText(_translate("MainWindow", "Zero Degree"))
        self.label_exposures.setText(_translate("MainWindow", "?"))
        self.label_start_ct.setText(_translate("MainWindow", "?"))
        self.label_origin.setText(_translate("MainWindow", "?"))
        self.label_zero_degree.setText(_translate("MainWindow", "?"))
        self.label_zero_z.setText(_translate("MainWindow", "?"))
        self.execute_label.setText(_translate("MainWindow", "Execute"))
        self.send_parameters.setText(_translate("MainWindow", "Send Parameters"))
        self.download_json.setText(_translate("MainWindow", "Download JSON"))
        self.upload_json.setText(_translate("MainWindow", "Upload JSON"))
        self.clear_fields.setText(_translate("MainWindow", "Clear Fields"))
        self.file_name.setText(_translate("MainWindow", "File name:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
