# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basic_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1012, 705)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background1 = QtWidgets.QWidget(self.centralwidget)
        self.background1.setGeometry(QtCore.QRect(20, 10, 311, 641))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.background1.setFont(font)
        self.background1.setStyleSheet("background-color: rgb(221, 221, 221)")
        self.background1.setObjectName("background1")
        self.mechanic_background = QtWidgets.QWidget(self.background1)
        self.mechanic_background.setGeometry(QtCore.QRect(0, 20, 311, 51))
        self.mechanic_background.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mechanic_background.setAutoFillBackground(False)
        self.mechanic_background.setStyleSheet("QWidget {\n"
"    background-color: #ffc355; /* cor de fundo amarela */\n"
"    /*border-radius: 10px;*/\n"
"\n"
"}\n"
"")
        self.mechanic_background.setObjectName("mechanic_background")
        self.mechanic_label = QtWidgets.QLabel(self.mechanic_background)
        self.mechanic_label.setGeometry(QtCore.QRect(90, 10, 121, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mechanic_label.setFont(font)
        self.mechanic_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mechanic_label.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.mechanic_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mechanic_label.setWordWrap(False)
        self.mechanic_label.setObjectName("mechanic_label")
        self.number_of_projections = QtWidgets.QLabel(self.background1)
        self.number_of_projections.setGeometry(QtCore.QRect(30, 90, 231, 31))
        self.number_of_projections.setMinimumSize(QtCore.QSize(225, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.number_of_projections.setFont(font)
        self.number_of_projections.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.number_of_projections.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.number_of_projections.setAlignment(QtCore.Qt.AlignCenter)
        self.number_of_projections.setWordWrap(False)
        self.number_of_projections.setObjectName("number_of_projections")
        self.oversample = QtWidgets.QLabel(self.background1)
        self.oversample.setGeometry(QtCore.QRect(40, 220, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.oversample.setFont(font)
        self.oversample.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.oversample.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.oversample.setAlignment(QtCore.Qt.AlignCenter)
        self.oversample.setWordWrap(False)
        self.oversample.setObjectName("oversample")
        self.scan_height = QtWidgets.QLabel(self.background1)
        self.scan_height.setGeometry(QtCore.QRect(40, 350, 131, 45))
        self.scan_height.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.scan_height.setFont(font)
        self.scan_height.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scan_height.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.scan_height.setAlignment(QtCore.Qt.AlignCenter)
        self.scan_height.setWordWrap(False)
        self.scan_height.setObjectName("scan_height")
        self.pitch = QtWidgets.QLabel(self.background1)
        self.pitch.setGeometry(QtCore.QRect(50, 500, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pitch.setFont(font)
        self.pitch.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pitch.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.pitch.setAlignment(QtCore.Qt.AlignCenter)
        self.pitch.setWordWrap(False)
        self.pitch.setObjectName("pitch")
        self.input_box1 = QtWidgets.QSpinBox(self.background1)
        self.input_box1.setGeometry(QtCore.QRect(50, 130, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_box1.setFont(font)
        self.input_box1.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_box1.setPrefix("")
        self.input_box1.setMinimum(-999999999)
        self.input_box1.setMaximum(999999999)
        self.input_box1.setObjectName("input_box1")
        self.input_box2 = QtWidgets.QSpinBox(self.background1)
        self.input_box2.setGeometry(QtCore.QRect(50, 260, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_box2.setFont(font)
        self.input_box2.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_box2.setMinimum(-999999999)
        self.input_box2.setMaximum(999999999)
        self.input_box2.setObjectName("input_box2")
        self.input_box3 = QtWidgets.QSpinBox(self.background1)
        self.input_box3.setGeometry(QtCore.QRect(50, 400, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_box3.setFont(font)
        self.input_box3.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_box3.setMinimum(-999999999)
        self.input_box3.setMaximum(999999999)
        self.input_box3.setObjectName("input_box3")
        self.input_box4 = QtWidgets.QSpinBox(self.background1)
        self.input_box4.setGeometry(QtCore.QRect(50, 540, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_box4.setFont(font)
        self.input_box4.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_box4.setMinimum(-999999999)
        self.input_box4.setMaximum(999999999)
        self.input_box4.setObjectName("input_box4")
        self.label_pitch = QtWidgets.QLabel(self.background1)
        self.label_pitch.setGeometry(QtCore.QRect(120, 500, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_pitch.setFont(font)
        self.label_pitch.setStyleSheet("  color: blue; ")
        self.label_pitch.setObjectName("label_pitch")
        self.label_scan_height = QtWidgets.QLabel(self.background1)
        self.label_scan_height.setGeometry(QtCore.QRect(180, 360, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_scan_height.setFont(font)
        self.label_scan_height.setStyleSheet("  color: blue; ")
        self.label_scan_height.setObjectName("label_scan_height")
        self.label_oversample = QtWidgets.QLabel(self.background1)
        self.label_oversample.setGeometry(QtCore.QRect(170, 220, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_oversample.setFont(font)
        self.label_oversample.setStyleSheet("  color: blue; ")
        self.label_oversample.setObjectName("label_oversample")
        self.label_number_of_projections = QtWidgets.QLabel(self.background1)
        self.label_number_of_projections.setGeometry(QtCore.QRect(270, 90, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_number_of_projections.setFont(font)
        self.label_number_of_projections.setStyleSheet("  color: blue; ")
        self.label_number_of_projections.setObjectName("label_number_of_projections")
        self.background2 = QtWidgets.QWidget(self.centralwidget)
        self.background2.setGeometry(QtCore.QRect(350, 10, 311, 641))
        self.background2.setStyleSheet("background-color: rgb(221, 221, 221)")
        self.background2.setObjectName("background2")
        self.tube_background = QtWidgets.QWidget(self.background2)
        self.tube_background.setGeometry(QtCore.QRect(0, 20, 311, 51))
        self.tube_background.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tube_background.setAutoFillBackground(False)
        self.tube_background.setStyleSheet("QWidget {\n"
"    background-color: #ffc355; /* cor de fundo amarela */\n"
"    /*border-radius: 10px;*/\n"
"\n"
"}\n"
"")
        self.tube_background.setObjectName("tube_background")
        self.tube_label = QtWidgets.QLabel(self.tube_background)
        self.tube_label.setGeometry(QtCore.QRect(120, 10, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.tube_label.setFont(font)
        self.tube_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tube_label.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.tube_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tube_label.setWordWrap(False)
        self.tube_label.setObjectName("tube_label")
        self.detector_background = QtWidgets.QWidget(self.background2)
        self.detector_background.setGeometry(QtCore.QRect(0, 430, 311, 51))
        self.detector_background.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.detector_background.setAutoFillBackground(False)
        self.detector_background.setStyleSheet("QWidget {\n"
"    background-color: #ffc355; /* cor de fundo amarela */\n"
"    /*border-radius: 10px;*/\n"
"\n"
"}\n"
"")
        self.detector_background.setObjectName("detector_background")
        self.detector_label = QtWidgets.QLabel(self.detector_background)
        self.detector_label.setGeometry(QtCore.QRect(100, 10, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.detector_label.setFont(font)
        self.detector_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.detector_label.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.detector_label.setAlignment(QtCore.Qt.AlignCenter)
        self.detector_label.setWordWrap(False)
        self.detector_label.setObjectName("detector_label")
        self.input_box5 = QtWidgets.QSpinBox(self.background2)
        self.input_box5.setGeometry(QtCore.QRect(50, 130, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_box5.setFont(font)
        self.input_box5.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_box5.setMinimum(-999999999)
        self.input_box5.setMaximum(999999999)
        self.input_box5.setObjectName("input_box5")
        self.kv = QtWidgets.QLabel(self.background2)
        self.kv.setGeometry(QtCore.QRect(50, 90, 51, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.kv.setFont(font)
        self.kv.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.kv.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.kv.setAlignment(QtCore.Qt.AlignCenter)
        self.kv.setWordWrap(False)
        self.kv.setObjectName("kv")
        self.mas = QtWidgets.QLabel(self.background2)
        self.mas.setGeometry(QtCore.QRect(50, 200, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.mas.setFont(font)
        self.mas.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mas.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.mas.setAlignment(QtCore.Qt.AlignCenter)
        self.mas.setWordWrap(False)
        self.mas.setObjectName("mas")
        self.input_box6 = QtWidgets.QSpinBox(self.background2)
        self.input_box6.setGeometry(QtCore.QRect(50, 240, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_box6.setFont(font)
        self.input_box6.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_box6.setMinimum(-999999999)
        self.input_box6.setMaximum(999999999)
        self.input_box6.setObjectName("input_box6")
        self.focus = QtWidgets.QLabel(self.background2)
        self.focus.setGeometry(QtCore.QRect(50, 300, 71, 45))
        self.focus.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.focus.setFont(font)
        self.focus.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.focus.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.focus.setAlignment(QtCore.Qt.AlignCenter)
        self.focus.setWordWrap(False)
        self.focus.setObjectName("focus")
        self.input_box7 = QtWidgets.QSpinBox(self.background2)
        self.input_box7.setGeometry(QtCore.QRect(50, 350, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_box7.setFont(font)
        self.input_box7.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_box7.setMinimum(-999999999)
        self.input_box7.setMaximum(999999999)
        self.input_box7.setObjectName("input_box7")
        self.acquire_mode = QtWidgets.QLabel(self.background2)
        self.acquire_mode.setGeometry(QtCore.QRect(50, 500, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.acquire_mode.setFont(font)
        self.acquire_mode.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.acquire_mode.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.acquire_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.acquire_mode.setWordWrap(False)
        self.acquire_mode.setObjectName("acquire_mode")
        self.input_box8 = QtWidgets.QSpinBox(self.background2)
        self.input_box8.setGeometry(QtCore.QRect(50, 540, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_box8.setFont(font)
        self.input_box8.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_box8.setMinimum(-999999999)
        self.input_box8.setMaximum(999999999)
        self.input_box8.setObjectName("input_box8")
        self.label_kv = QtWidgets.QLabel(self.background2)
        self.label_kv.setGeometry(QtCore.QRect(110, 90, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_kv.setFont(font)
        self.label_kv.setStyleSheet("  color: blue; ")
        self.label_kv.setObjectName("label_kv")
        self.label_mas = QtWidgets.QLabel(self.background2)
        self.label_mas.setGeometry(QtCore.QRect(120, 200, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_mas.setFont(font)
        self.label_mas.setStyleSheet("  color: blue; ")
        self.label_mas.setObjectName("label_mas")
        self.label_focus = QtWidgets.QLabel(self.background2)
        self.label_focus.setGeometry(QtCore.QRect(130, 310, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_focus.setFont(font)
        self.label_focus.setStyleSheet("  color: blue; ")
        self.label_focus.setObjectName("label_focus")
        self.label_acquire_mode = QtWidgets.QLabel(self.background2)
        self.label_acquire_mode.setGeometry(QtCore.QRect(210, 500, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_acquire_mode.setFont(font)
        self.label_acquire_mode.setStyleSheet("  color: blue; ")
        self.label_acquire_mode.setObjectName("label_acquire_mode")
        self.background3 = QtWidgets.QWidget(self.centralwidget)
        self.background3.setGeometry(QtCore.QRect(680, 10, 311, 641))
        self.background3.setStyleSheet("background-color: rgb(221, 221, 221)")
        self.background3.setObjectName("background3")
        self.execute_background = QtWidgets.QWidget(self.background3)
        self.execute_background.setGeometry(QtCore.QRect(0, 20, 311, 51))
        self.execute_background.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.execute_background.setAutoFillBackground(False)
        self.execute_background.setStyleSheet("QWidget {\n"
"    background-color: #ffc355; /* cor de fundo amarela */\n"
"    /*border-radius: 10px;*/\n"
"\n"
"}\n"
"")
        self.execute_background.setObjectName("execute_background")
        self.execute_label = QtWidgets.QLabel(self.execute_background)
        self.execute_label.setGeometry(QtCore.QRect(100, 10, 111, 30))
        self.execute_label.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.execute_label.setFont(font)
        self.execute_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.execute_label.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.execute_label.setAlignment(QtCore.Qt.AlignCenter)
        self.execute_label.setWordWrap(False)
        self.execute_label.setObjectName("execute_label")
        self.send_parameters = QtWidgets.QPushButton(self.background3)
        self.send_parameters.setGeometry(QtCore.QRect(60, 110, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.send_parameters.setFont(font)
        self.send_parameters.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.send_parameters.setObjectName("send_parameters")
        self.download_json = QtWidgets.QPushButton(self.background3)
        self.download_json.setGeometry(QtCore.QRect(60, 280, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.download_json.setFont(font)
        self.download_json.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.download_json.setObjectName("download_json")
        self.upload_json = QtWidgets.QPushButton(self.background3)
        self.upload_json.setGeometry(QtCore.QRect(60, 350, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.upload_json.setFont(font)
        self.upload_json.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.upload_json.setObjectName("upload_json")
        self.clear_fields = QtWidgets.QPushButton(self.background3)
        self.clear_fields.setGeometry(QtCore.QRect(60, 490, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.clear_fields.setFont(font)
        self.clear_fields.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.clear_fields.setObjectName("clear_fields")
        self.file_name = QtWidgets.QLabel(self.background3)
        self.file_name.setGeometry(QtCore.QRect(60, 220, 90, 16))
        self.file_name.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.file_name.setFont(font)
        self.file_name.setObjectName("file_name")
        self.file_name_input = QtWidgets.QLineEdit(self.background3)
        self.file_name_input.setGeometry(QtCore.QRect(60, 240, 181, 31))
        self.file_name_input.setStyleSheet("QLineEdit {\n"
"    background-color: white; /* Define o fundo como branco */\n"
"    border: 1px solid #a9a9a9; /* Define uma borda sólida com cor cinza */\n"
"    border-radius: 5px; /* Cantos arredondados com raio de 5px */\n"
"    padding: 1px 3px; /* Espaçamento interno para o texto não tocar a borda */\n"
"}\n"
"")
        self.file_name_input.setObjectName("file_name_input")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1012, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "basic_settings"))
        self.mechanic_label.setText(_translate("MainWindow", "Mechanic"))
        self.number_of_projections.setText(_translate("MainWindow", "Number of Projections"))
        self.oversample.setText(_translate("MainWindow", "Oversample"))
        self.scan_height.setText(_translate("MainWindow", "Scan Height"))
        self.pitch.setText(_translate("MainWindow", "Pitch"))
        self.label_pitch.setText(_translate("MainWindow", "?"))
        self.label_scan_height.setText(_translate("MainWindow", "?"))
        self.label_oversample.setText(_translate("MainWindow", "?"))
        self.label_number_of_projections.setText(_translate("MainWindow", "?"))
        self.tube_label.setText(_translate("MainWindow", "Tube"))
        self.detector_label.setText(_translate("MainWindow", "Detector"))
        self.kv.setText(_translate("MainWindow", "kV"))
        self.mas.setText(_translate("MainWindow", "mAs"))
        self.focus.setText(_translate("MainWindow", "Focus"))
        self.acquire_mode.setText(_translate("MainWindow", "Acquire Mode"))
        self.label_kv.setText(_translate("MainWindow", "?"))
        self.label_mas.setText(_translate("MainWindow", "?"))
        self.label_focus.setText(_translate("MainWindow", "?"))
        self.label_acquire_mode.setText(_translate("MainWindow", "?"))
        self.execute_label.setText(_translate("MainWindow", "Execute"))
        self.send_parameters.setText(_translate("MainWindow", "Send Parameters"))
        self.download_json.setText(_translate("MainWindow", "Download JSON"))
        self.upload_json.setText(_translate("MainWindow", "Upload JSON"))
        self.clear_fields.setText(_translate("MainWindow", "Clear Fields"))
        self.file_name.setText(_translate("MainWindow", "File name:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
