# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'advanced_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1012, 710)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background3 = QtWidgets.QWidget(self.centralwidget)
        self.background3.setGeometry(QtCore.QRect(680, 10, 311, 641))
        self.background3.setStyleSheet("background-color: rgb(221, 221, 221)")
        self.background3.setObjectName("background3")
        self.execute_background = QtWidgets.QWidget(self.background3)
        self.execute_background.setGeometry(QtCore.QRect(0, 20, 311, 51))
        self.execute_background.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.execute_background.setAutoFillBackground(False)
        self.execute_background.setStyleSheet("QWidget {\n"
"    background-color: #ffc355; /* cor de fundo amarela */\n"
"    /*border-radius: 10px;*/\n"
"\n"
"}\n"
"")
        self.execute_background.setObjectName("execute_background")
        self.execute_label = QtWidgets.QLabel(self.execute_background)
        self.execute_label.setGeometry(QtCore.QRect(100, 10, 100, 30))
        self.execute_label.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.execute_label.setFont(font)
        self.execute_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.execute_label.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.execute_label.setAlignment(QtCore.Qt.AlignCenter)
        self.execute_label.setWordWrap(False)
        self.execute_label.setObjectName("execute_label")
        self.send_parameters = QtWidgets.QPushButton(self.background3)
        self.send_parameters.setGeometry(QtCore.QRect(60, 110, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.send_parameters.setFont(font)
        self.send_parameters.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.send_parameters.setObjectName("send_parameters")
        self.download_json = QtWidgets.QPushButton(self.background3)
        self.download_json.setGeometry(QtCore.QRect(60, 280, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.download_json.setFont(font)
        self.download_json.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.download_json.setObjectName("download_json")
        self.upload_json = QtWidgets.QPushButton(self.background3)
        self.upload_json.setGeometry(QtCore.QRect(60, 350, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.upload_json.setFont(font)
        self.upload_json.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.upload_json.setObjectName("upload_json")
        self.clear_fields = QtWidgets.QPushButton(self.background3)
        self.clear_fields.setGeometry(QtCore.QRect(60, 490, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.clear_fields.setFont(font)
        self.clear_fields.setStyleSheet("QWidget {\n"
"    background-color: #FFB62D; /* cor de fundo amarela */\n"
"    border-radius: 10px; /* bordas arredondadas */\n"
"    border: 1px solid black; /* borda sólida preta */\n"
"}\n"
"")
        self.clear_fields.setObjectName("clear_fields")
        self.file_name = QtWidgets.QLabel(self.background3)
        self.file_name.setGeometry(QtCore.QRect(60, 220, 90, 16))
        self.file_name.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.file_name.setFont(font)
        self.file_name.setObjectName("file_name")
        self.file_name_input = QtWidgets.QLineEdit(self.background3)
        self.file_name_input.setGeometry(QtCore.QRect(60, 240, 181, 31))
        self.file_name_input.setStyleSheet("QLineEdit {\n"
"    background-color: white; /* Define o fundo como branco */\n"
"    border: 1px solid #a9a9a9; /* Define uma borda sólida com cor cinza */\n"
"    border-radius: 5px; /* Cantos arredondados com raio de 5px */\n"
"    padding: 1px 3px; /* Espaçamento interno para o texto não tocar a borda */\n"
"}\n"
"")
        self.file_name_input.setObjectName("file_name_input")
        self.background1 = QtWidgets.QWidget(self.centralwidget)
        self.background1.setGeometry(QtCore.QRect(20, 10, 311, 641))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.background1.setFont(font)
        self.background1.setStyleSheet("background-color: rgb(221, 221, 221)")
        self.background1.setObjectName("background1")
        self.detector_background = QtWidgets.QWidget(self.background1)
        self.detector_background.setGeometry(QtCore.QRect(0, 20, 311, 51))
        self.detector_background.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.detector_background.setAutoFillBackground(False)
        self.detector_background.setStyleSheet("QWidget {\n"
"    background-color: #ffc355; /* cor de fundo amarela */\n"
"    /*border-radius: 10px;*/\n"
"\n"
"}\n"
"")
        self.detector_background.setObjectName("detector_background")
        self.detector_label = QtWidgets.QLabel(self.detector_background)
        self.detector_label.setGeometry(QtCore.QRect(90, 10, 120, 30))
        self.detector_label.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.detector_label.setFont(font)
        self.detector_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.detector_label.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.detector_label.setAlignment(QtCore.Qt.AlignCenter)
        self.detector_label.setWordWrap(False)
        self.detector_label.setObjectName("detector_label")
        self.number_of_exposures = QtWidgets.QLabel(self.background1)
        self.number_of_exposures.setGeometry(QtCore.QRect(30, 90, 230, 35))
        self.number_of_exposures.setMinimumSize(QtCore.QSize(230, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.number_of_exposures.setFont(font)
        self.number_of_exposures.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.number_of_exposures.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.number_of_exposures.setAlignment(QtCore.Qt.AlignCenter)
        self.number_of_exposures.setWordWrap(False)
        self.number_of_exposures.setObjectName("number_of_exposures")
        self.acquire_mode = QtWidgets.QLabel(self.background1)
        self.acquire_mode.setGeometry(QtCore.QRect(40, 190, 150, 30))
        self.acquire_mode.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.acquire_mode.setFont(font)
        self.acquire_mode.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.acquire_mode.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.acquire_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.acquire_mode.setWordWrap(False)
        self.acquire_mode.setObjectName("acquire_mode")
        self.trigger_mode = QtWidgets.QLabel(self.background1)
        self.trigger_mode.setGeometry(QtCore.QRect(40, 300, 145, 35))
        self.trigger_mode.setMinimumSize(QtCore.QSize(145, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.trigger_mode.setFont(font)
        self.trigger_mode.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.trigger_mode.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.trigger_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.trigger_mode.setWordWrap(False)
        self.trigger_mode.setObjectName("trigger_mode")
        self.sensor_bias = QtWidgets.QLabel(self.background1)
        self.sensor_bias.setGeometry(QtCore.QRect(40, 410, 130, 30))
        self.sensor_bias.setMinimumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sensor_bias.setFont(font)
        self.sensor_bias.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sensor_bias.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.sensor_bias.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_bias.setWordWrap(False)
        self.sensor_bias.setObjectName("sensor_bias")
        self.input_box1 = QtWidgets.QSpinBox(self.background1)
        self.input_box1.setGeometry(QtCore.QRect(50, 130, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_box1.setFont(font)
        self.input_box1.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_box1.setMinimum(-999999999)
        self.input_box1.setMaximum(999999999)
        self.input_box1.setObjectName("input_box1")
        self.input_box2 = QtWidgets.QSpinBox(self.background1)
        self.input_box2.setGeometry(QtCore.QRect(50, 230, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_box2.setFont(font)
        self.input_box2.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_box2.setMinimum(-999999999)
        self.input_box2.setMaximum(999999999)
        self.input_box2.setObjectName("input_box2")
        self.input_box3 = QtWidgets.QSpinBox(self.background1)
        self.input_box3.setGeometry(QtCore.QRect(50, 340, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_box3.setFont(font)
        self.input_box3.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_box3.setMinimum(-999999999)
        self.input_box3.setMaximum(999999999)
        self.input_box3.setObjectName("input_box3")
        self.input_box4 = QtWidgets.QSpinBox(self.background1)
        self.input_box4.setGeometry(QtCore.QRect(50, 450, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_box4.setFont(font)
        self.input_box4.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_box4.setMinimum(-999999999)
        self.input_box4.setMaximum(999999999)
        self.input_box4.setObjectName("input_box4")
        self.input_box5 = QtWidgets.QSpinBox(self.background1)
        self.input_box5.setGeometry(QtCore.QRect(50, 560, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_box5.setFont(font)
        self.input_box5.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_box5.setMinimum(-999999999)
        self.input_box5.setMaximum(999999999)
        self.input_box5.setObjectName("input_box5")
        self.gain_all = QtWidgets.QLabel(self.background1)
        self.gain_all.setGeometry(QtCore.QRect(40, 520, 90, 30))
        self.gain_all.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.gain_all.setFont(font)
        self.gain_all.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gain_all.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.gain_all.setAlignment(QtCore.Qt.AlignCenter)
        self.gain_all.setWordWrap(False)
        self.gain_all.setObjectName("gain_all")
        self.label_gain_all = QtWidgets.QLabel(self.background1)
        self.label_gain_all.setGeometry(QtCore.QRect(140, 520, 16, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_gain_all.setFont(font)
        self.label_gain_all.setStyleSheet("  color: blue; ")
        self.label_gain_all.setObjectName("label_gain_all")
        self.label_sensor_bias = QtWidgets.QLabel(self.background1)
        self.label_sensor_bias.setGeometry(QtCore.QRect(180, 410, 16, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_sensor_bias.setFont(font)
        self.label_sensor_bias.setStyleSheet("  color: blue; ")
        self.label_sensor_bias.setObjectName("label_sensor_bias")
        self.label_trigger_mode = QtWidgets.QLabel(self.background1)
        self.label_trigger_mode.setGeometry(QtCore.QRect(190, 300, 16, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_trigger_mode.setFont(font)
        self.label_trigger_mode.setStyleSheet("  color: blue; ")
        self.label_trigger_mode.setObjectName("label_trigger_mode")
        self.label_acquire_mode = QtWidgets.QLabel(self.background1)
        self.label_acquire_mode.setGeometry(QtCore.QRect(210, 190, 21, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_acquire_mode.setFont(font)
        self.label_acquire_mode.setStyleSheet("  color: blue; ")
        self.label_acquire_mode.setObjectName("label_acquire_mode")
        self.label_number_of_exposures = QtWidgets.QLabel(self.background1)
        self.label_number_of_exposures.setGeometry(QtCore.QRect(270, 90, 16, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_number_of_exposures.setFont(font)
        self.label_number_of_exposures.setStyleSheet("  color: blue; ")
        self.label_number_of_exposures.setObjectName("label_number_of_exposures")
        self.background2 = QtWidgets.QWidget(self.centralwidget)
        self.background2.setGeometry(QtCore.QRect(350, 10, 311, 641))
        self.background2.setStyleSheet("background-color: rgb(221, 221, 221)")
        self.background2.setObjectName("background2")
        self.mechanic_background = QtWidgets.QWidget(self.background2)
        self.mechanic_background.setGeometry(QtCore.QRect(0, 20, 311, 51))
        self.mechanic_background.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mechanic_background.setAutoFillBackground(False)
        self.mechanic_background.setStyleSheet("QWidget {\n"
"    background-color: #ffc355; /* cor de fundo amarela */\n"
"    /*border-radius: 10px;*/\n"
"\n"
"}\n"
"")
        self.mechanic_background.setObjectName("mechanic_background")
        self.mechanic_label = QtWidgets.QLabel(self.mechanic_background)
        self.mechanic_label.setGeometry(QtCore.QRect(90, 10, 130, 30))
        self.mechanic_label.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mechanic_label.setFont(font)
        self.mechanic_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mechanic_label.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.mechanic_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mechanic_label.setWordWrap(False)
        self.mechanic_label.setObjectName("mechanic_label")
        self.tube_background = QtWidgets.QWidget(self.background2)
        self.tube_background.setGeometry(QtCore.QRect(0, 430, 311, 51))
        self.tube_background.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tube_background.setAutoFillBackground(False)
        self.tube_background.setStyleSheet("QWidget {\n"
"    background-color: #ffc355; /* cor de fundo amarela */\n"
"    /*border-radius: 10px;*/\n"
"\n"
"}\n"
"")
        self.tube_background.setObjectName("tube_background")
        self.tube_label = QtWidgets.QLabel(self.tube_background)
        self.tube_label.setGeometry(QtCore.QRect(100, 10, 91, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.tube_label.setFont(font)
        self.tube_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tube_label.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.tube_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tube_label.setWordWrap(False)
        self.tube_label.setObjectName("tube_label")
        self.input_box6 = QtWidgets.QSpinBox(self.background2)
        self.input_box6.setGeometry(QtCore.QRect(50, 180, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_box6.setFont(font)
        self.input_box6.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_box6.setMinimum(-999999999)
        self.input_box6.setMaximum(999999999)
        self.input_box6.setObjectName("input_box6")
        self.micro_step_z = QtWidgets.QLabel(self.background2)
        self.micro_step_z.setGeometry(QtCore.QRect(40, 140, 130, 35))
        self.micro_step_z.setMinimumSize(QtCore.QSize(130, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.micro_step_z.setFont(font)
        self.micro_step_z.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.micro_step_z.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.micro_step_z.setAlignment(QtCore.Qt.AlignCenter)
        self.micro_step_z.setWordWrap(False)
        self.micro_step_z.setObjectName("micro_step_z")
        self.micro_step_angular = QtWidgets.QLabel(self.background2)
        self.micro_step_angular.setGeometry(QtCore.QRect(40, 290, 200, 30))
        self.micro_step_angular.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.micro_step_angular.setFont(font)
        self.micro_step_angular.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.micro_step_angular.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.micro_step_angular.setAlignment(QtCore.Qt.AlignCenter)
        self.micro_step_angular.setWordWrap(False)
        self.micro_step_angular.setObjectName("micro_step_angular")
        self.input_box7 = QtWidgets.QSpinBox(self.background2)
        self.input_box7.setGeometry(QtCore.QRect(50, 330, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_box7.setFont(font)
        self.input_box7.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_box7.setMinimum(-999999999)
        self.input_box7.setMaximum(999999999)
        self.input_box7.setObjectName("input_box7")
        self.threshold = QtWidgets.QLabel(self.background2)
        self.threshold.setGeometry(QtCore.QRect(40, 520, 110, 35))
        self.threshold.setMinimumSize(QtCore.QSize(110, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.threshold.setFont(font)
        self.threshold.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.threshold.setStyleSheet("QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.threshold.setAlignment(QtCore.Qt.AlignCenter)
        self.threshold.setWordWrap(False)
        self.threshold.setObjectName("threshold")
        self.input_box8 = QtWidgets.QSpinBox(self.background2)
        self.input_box8.setGeometry(QtCore.QRect(50, 560, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_box8.setFont(font)
        self.input_box8.setStyleSheet("QSpinBox {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 5px; \n"
"    padding: 1px 3px; \n"
"}\n"
"\n"
"\n"
"")
        self.input_box8.setMinimum(-999999999)
        self.input_box8.setMaximum(999999999)
        self.input_box8.setObjectName("input_box8")
        self.label_micro_step_z = QtWidgets.QLabel(self.background2)
        self.label_micro_step_z.setGeometry(QtCore.QRect(180, 140, 16, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_micro_step_z.setFont(font)
        self.label_micro_step_z.setStyleSheet("  color: blue; ")
        self.label_micro_step_z.setObjectName("label_micro_step_z")
        self.label__micro_step_angular = QtWidgets.QLabel(self.background2)
        self.label__micro_step_angular.setGeometry(QtCore.QRect(240, 290, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label__micro_step_angular.setFont(font)
        self.label__micro_step_angular.setStyleSheet("  color: blue; ")
        self.label__micro_step_angular.setObjectName("label__micro_step_angular")
        self.label_threshold = QtWidgets.QLabel(self.background2)
        self.label_threshold.setGeometry(QtCore.QRect(170, 520, 16, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_threshold.setFont(font)
        self.label_threshold.setStyleSheet("  color: blue; ")
        self.label_threshold.setObjectName("label_threshold")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1012, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "advanced_settings"))
        self.execute_label.setText(_translate("MainWindow", "Execute"))
        self.send_parameters.setText(_translate("MainWindow", "Send Parameters"))
        self.download_json.setText(_translate("MainWindow", "Download JSON"))
        self.upload_json.setText(_translate("MainWindow", "Upload JSON"))
        self.clear_fields.setText(_translate("MainWindow", "Clear Fields"))
        self.file_name.setText(_translate("MainWindow", "File name:"))
        self.detector_label.setText(_translate("MainWindow", "Detector"))
        self.number_of_exposures.setText(_translate("MainWindow", "Number of Exposures"))
        self.acquire_mode.setText(_translate("MainWindow", "Acquire Mode"))
        self.trigger_mode.setText(_translate("MainWindow", "Trigger Mode"))
        self.sensor_bias.setText(_translate("MainWindow", "Sensor Bias"))
        self.gain_all.setText(_translate("MainWindow", "Gain all"))
        self.label_gain_all.setText(_translate("MainWindow", "?"))
        self.label_sensor_bias.setText(_translate("MainWindow", "?"))
        self.label_trigger_mode.setText(_translate("MainWindow", "?"))
        self.label_acquire_mode.setText(_translate("MainWindow", "?"))
        self.label_number_of_exposures.setText(_translate("MainWindow", "?"))
        self.mechanic_label.setText(_translate("MainWindow", "Mechanic"))
        self.tube_label.setText(_translate("MainWindow", "Tube"))
        self.micro_step_z.setText(_translate("MainWindow", "Micro step Z"))
        self.micro_step_angular.setText(_translate("MainWindow", "Micro step angular"))
        self.threshold.setText(_translate("MainWindow", "Threshold"))
        self.label_micro_step_z.setText(_translate("MainWindow", "?"))
        self.label__micro_step_angular.setText(_translate("MainWindow", "?"))
        self.label_threshold.setText(_translate("MainWindow", "?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
